Barratt/direction v3.1
Drewbi/buildings-in-landscape-uwa pull request #18
Opened 2020-10-07 05:37 UTC by 21964392

2020-10-07 07:07 UTC, 21964392 commented
Hekk

2020-10-08 15:16 UTC, Drewbi commented on src/data/location.json
> +    "nonavMarkers": [
We should remove these now, I don't think we'll need them later and it will just confuse us

2020-10-08 15:22 UTC, Drewbi requested changes
Could you also run `yarn lint` to make sure all the white space and formatting is correct?

2020-10-08 15:22 UTC, Drewbi commented on src/data/location.json
> +      "scale": 0.1
I think it works if you just remove the position and scale fields, was there a reason we were leaving these in?

2020-10-09 10:19 UTC, merged